#theme= ""                    #默认使用default
#enableHtmlSuffix = false     #关闭html后缀，默认开启
#frontMatterSeparator = "+++"  #前辅文分隔符，默认为"---"
#pageSize = 10                 #分页参数，默认为10

# site your menus             # 配置目录，根据权重排序
[[menus.main]]            
  name = "首页"
  weight = 10
  id = "home"
  url = "/"

  
[params]                      #额外配置
#author=heemooo