# This is a simple configuration.
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "127.0.0.1"
title = "管他谁谁谁"
#theme= "hugo-theme-amaze"
enableHtmlSuffix = true
#前辅文分隔符
frontMatterSeparator = "+++"

# site your menus              # 配置目录
[[menus.main]]            
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menus.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/post.html"
[[menus.main]]
  name = "标签"
  weight = 40
  identifier = "tags"
  url = "/tags.html"
[[menus.main]]
  name = "categories"
  weight = 30
  identifier = "categories"
  url = "/categories.html"

  
[params]
  backgroundUrl = "/images/snowgitlabk.jpg"
  logo = "/img/logo.png"
  since = "2019"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary
  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  SubTitle="逍遥天地外，不在五行中"
  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"
  [params.social]                                         # 社交链接
    GitHub = "heemooo"
    QQ = "396518407"
    WeiBo = "https://weibo.com/1736003065/profile?topnav=1&wvr=6&is_all=1"